language: java
sudo: false
install: true
jdk:
- oraclejdk8
addons:
  sonarqube:
    organization: "sabp"
    token:
      secure: DHHlfLEH9KpCtygeNNrgPIVAjqvii2CbbUXJBlANOUE9XociwEklEscze7Q8nMq79J0p9COWdcbl13T+AfWmY1m5B83GPmJmgSDR9ttgmbS7twcl4Ury8wyP9UstCERWDC+KXRH5AVmX5VYgsc64YpvS3NziM294kVCMryiOiBmeBv/6+QudVP2AoHXc2/UzxIc5ZlQZPrRtwxel1Tz7Hj0fUmzdUDfwwe/+JEmMKV2Jc90RucvMtwOl5STB7IL3YyBTN9763euSJ1UCMdxUA1AYZqoC1VmhDsJbrazxGhguDa9CCNmsWbJ55HfZ/ihgJQIOXtezNn/xGlCq4PX2sKTXmowZgfrdRcPChT6WW+DpoUebxGp91i/TagKhTNTo+HzpHedvvHtvjTA1sCC8bAuND2GrYGz4ZYs++2qKS0VeGnwjPjlhuOCZhiD3iAlGhbOzGnlI18HrylE5+W8QHzef9xFnbsEmIhsvSYryZptJ87XRHj8nfeeTyHsgbnhIto3dAmVVfccU4EGwGBf5OWwlPd7ytw1YaCi/bY4/BseCxzprofxTOyVePpTSHubPIOPxUOlnt6J3ELOu8E/HaHmSJKtJsCnOJHV9D+BIrkF3tCdziTjgwUqJ55aR7GU+EKAEgLlIK+TBW9YBnGBeWpR2DgX0EHxxM5BXe2XK1SU=
  branches:
  - master
script:
- mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar coveralls:report
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email: false
